### ISSUE TITLE
Northcliff - wrong times

### ISSUE THREAD

**Issue by cytracon** [Ruandv/Chrome_Eskom_Extension_Typescript#16]
Hi, thank you for your fantastic extension. Northcliff (Johanneburg) shows wrong times? Would you please check? Thanks!

**Comment by Ruandv** [comment]
I will try to find the new times and do an update if there are any.

Please can you tell me which areas you are experiencing issues with?

**Comment by cytracon** [comment]
Thank you, Northcliff Ext. 12

**Comment by Ruandv** [comment]
I have identified the issue and will close this ticket as soon as the change has been deployed. 

**Reason**: 
**Northcliff Ext 12** is part of **Block 2** and the Northcliff record that I am displaying in the app is part of **Block 7**. 

**Laternative**: 
As an alternative you can also look at the schedule for one of these suburbs they all form part of Block 2. 
- Berario
- Emmarentia
- Fairlands
- Greenside

**Comment by Ruandv** [comment]
@cytracon you can check the new version should have all the Northcliff areas. 
Ext 12 falls under "Northcliff Ext"
![Uploading image.png…]()
