### ISSUE TITLE
No suburbs for City of Cape Town

### ISSUE THREAD

**Issue by wolvyreen** [Ruandv/Chrome_Eskom_Extension_Typescript#8]
**Describe the bug**
When selecting "Western Cape" -> "City of Cape Town" there are no suburbs listed at all preventing anyone from adding an area that falls under City of Cape Town.

**Expected behavior**
A list of suburbs should show for selection

**Screenshots**
![image](https://github.com/Ruandv/sa_loadshedding_ext/assets/8437176/42be4c4a-26ca-49f1-97a1-1b4bcaa63feb)

**Additional context**
No other info to add

**Comment by Ruandv** [comment]
Please make sure you have the latest version of the extension (Ver.2.0.24) this issue is now resolved.
